server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://emrs.xyz:7001/eureka,http://emrs.xyz:7002/eureka
  instance:
    instance-id: order80
    prefer-ip-address: true