server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lihang1046750274/springcloud.git
          search-paths:
            - springcloud
  rabbitmq:
    host: emrs.xyz
    username: guest
    password: guest
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://emrs.xyz:7001/eureka,http://emrs.xyz:7002/eureka
    fetch-registry: true
    register-with-eureka: true

  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
    instance-id: config-center3344
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
