server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://emrs.xyz:7001/eureka/
  server:
    # 关闭保护机制，默认true
    enable-self-preservation: false
    # 剔除失效服务间隔，默认60000
    eviction-interval-timer-in-ms: 10000