server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001  # eureka服务端实例名字
  client:
    fetch-registry: false #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    register-with-eureka: false #表识不向注册中心注册自己
    service-url:
      defaultZone: http://emrs.xyz:7002/eureka/ #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址

    #    Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认30秒)
#    lease-renewal-interval-in-seconds: 1
    #    Eureka服务端在收到最后一次心跳后等待的时间上线，单位是秒(默认是90秒)，超时将剔除服务
#    lease-expiration-duration-in-seconds: 2
  server:
    # 关闭保护机制，默认true
    enable-self-preservation: false
    # 剔除失效服务间隔，默认60000
    eviction-interval-timer-in-ms: 10000