server:
  port: 9001

spring:
  application:
    name: nacos-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: emrs.xyz:8848
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
management:
  endpoints:
    web:
      exposure:
        include: '*'
