server:
  port: 80
spring:
  application:
    name: cloud-consumer-feign-order80
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://emrs.xyz:7001/eureka,http://emrs.xyz:7002/eureka
  instance:
    instance-id: order80
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔
    lease-renewal-interval-in-seconds: 5
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除
    lease-expiration-duration-in-seconds: 10
# 开启OpenFeign客户端超时控制
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
# 开启日志的feign客户端
logging:
  level:
    com.sy.springcloud.service.PaymentService: debug
