server:
  port: 83

spring:
  application:
    name: nacos-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: emrs.xyz:8848
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
service-url:
  nacos-provider-service: http://nacos-provider-payment

management:
  endpoints:
    web:
      exposure:
        include: '*'
