server:
  port: 8001

spring:
  application:
    name: provider-hystrix-payment8001

# 注册到eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://emrs.xyz:7001/eureka/,http://emrs.xyz:7002/eureka/
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
